name: Tests
on: [push]
jobs:
  js-wrapper-test:
    name: "Test JS wrapper"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Install developer dependencies
        run: npm install --save-dev
      - name: Test da code
        run: npm test